# Generated by Django 5.2.2 on 2025-06-05 11:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Soal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pertanyaan', models.TextField()),
                ('tipe', models.CharField(default='pilihan_ganda', max_length=20)),
                ('pilihan_a', models.CharField(blank=True, max_length=255, null=True)),
                ('pilihan_b', models.CharField(blank=True, max_length=255, null=True)),
                ('pilihan_c', models.CharField(blank=True, max_length=255, null=True)),
                ('pilihan_d', models.CharField(blank=True, max_length=255, null=True)),
                ('pilihan_e', models.CharField(blank=True, max_length=255, null=True)),
                ('jawaban_benar', models.CharField(max_length=10)),
                ('aktif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=100)),
                ('nisn', models.CharField(max_length=20, unique=True)),
                ('nik', models.CharField(max_length=20, unique=True)),
                ('tempat_lahir', models.CharField(max_length=50)),
                ('tanggal_lahir', models.DateField()),
                ('jenis_kelamin', models.CharField(max_length=10)),
                ('agama', models.CharField(max_length=20)),
                ('alamat', models.TextField()),
                ('telepon', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100)),
                ('status_pendaftaran', models.CharField(default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='siswa', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SekolahAsal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_sekolah', models.CharField(max_length=100)),
                ('alamat_sekolah', models.TextField()),
                ('tahun_lulus', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('siswa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sekolah_asal', to='siswa.siswa')),
            ],
        ),
        migrations.CreateModel(
            name='OrangTua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_ayah', models.CharField(max_length=100)),
                ('nama_ibu', models.CharField(max_length=100)),
                ('pekerjaan_ayah', models.CharField(max_length=50)),
                ('pekerjaan_ibu', models.CharField(max_length=50)),
                ('telepon_ayah', models.CharField(max_length=15)),
                ('telepon_ibu', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('siswa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orang_tua', to='siswa.siswa')),
            ],
        ),
        migrations.CreateModel(
            name='Dokumen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_dokumen', models.CharField(max_length=50)),
                ('file_path', models.CharField(max_length=200)),
                ('status', models.CharField(default='Diupload', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dokumen', to='siswa.siswa')),
            ],
        ),
        migrations.CreateModel(
            name='JawabanSiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jawaban', models.CharField(max_length=255)),
                ('benar', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jawaban_soal', to='siswa.siswa')),
                ('soal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jawaban_siswa', to='siswa.soal')),
            ],
        ),
        migrations.CreateModel(
            name='Verifikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Menunggu', max_length=20)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('tanggal_verifikasi', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifikasi_admin', to=settings.AUTH_USER_MODEL)),
                ('siswa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verifikasi', to='siswa.siswa')),
            ],
        ),
    ]
