# Generated by Django 5.2.2 on 2025-06-05 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siswa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orangtua',
            name='nik_ayah',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='orangtua',
            name='nik_ibu',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='orangtua',
            name='pendidikan_ayah',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orangtua',
            name='pendidikan_ibu',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orangtua',
            name='penghasilan_ayah',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orangtua',
            name='penghasilan_ibu',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sekolahasal',
            name='npsn',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='sekolahasal',
            name='rata_nilai_rapor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='siswa',
            name='berat_badan',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siswa',
            name='berkebutuhan_khusus',
            field=models.CharField(choices=[('Tidak Ada', 'Tidak Ada'), ('Tunanetra', 'Tunanetra'), ('Tunarungu', 'Tunarungu'), ('Tunadaksa', 'Tunadaksa'), ('Tunagrahita', 'Tunagrahita'), ('Lainnya', 'Lainnya')], default='Tidak Ada', max_length=50),
        ),
        migrations.AddField(
            model_name='siswa',
            name='golongan_darah',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='siswa',
            name='kelainan_jasmani',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siswa',
            name='kewarganegaraan',
            field=models.CharField(default='Indonesia', max_length=50),
        ),
        migrations.AddField(
            model_name='siswa',
            name='lingkar_kepala',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siswa',
            name='riwayat_penyakit',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siswa',
            name='telepon_rumah',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='siswa',
            name='tinggi_badan',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orangtua',
            name='telepon_ayah',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='orangtua',
            name='telepon_ibu',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='agama',
            field=models.CharField(choices=[('Islam', 'Islam'), ('Kristen', 'Kristen'), ('Katolik', 'Katolik'), ('Hindu', 'Hindu'), ('Buddha', 'Buddha'), ('Konghucu', 'Konghucu'), ('Lainnya', 'Lainnya')], max_length=20),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='jenis_kelamin',
            field=models.CharField(choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], max_length=10),
        ),
        migrations.CreateModel(
            name='BantuanSosial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kip_status', models.BooleanField(default=False)),
                ('kip_nomor', models.CharField(blank=True, max_length=50, null=True)),
                ('pkh_status', models.BooleanField(default=False)),
                ('pkh_nomor', models.CharField(blank=True, max_length=50, null=True)),
                ('kps_status', models.BooleanField(default=False)),
                ('kps_nomor', models.CharField(blank=True, max_length=50, null=True)),
                ('status_disabilitas', models.CharField(blank=True, max_length=50, null=True)),
                ('dokumen_kip_pkh', models.CharField(blank=True, max_length=200, null=True)),
                ('dokumen_tidak_mampu', models.CharField(blank=True, max_length=200, null=True)),
                ('dokumen_disabilitas', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('siswa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bantuan_sosial', to='siswa.siswa')),
            ],
        ),
        migrations.CreateModel(
            name='Domisili',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jarak_rumah_sekolah', models.DecimalField(decimal_places=2, max_digits=5)),
                ('waktu_tempuh', models.IntegerField(help_text='Waktu tempuh dalam menit')),
                ('moda_transportasi', models.CharField(max_length=50)),
                ('lama_tinggal_kk', models.IntegerField(help_text='Lama tinggal dalam tahun')),
                ('dokumen_kk', models.CharField(blank=True, max_length=200, null=True)),
                ('dokumen_ktp', models.CharField(blank=True, max_length=200, null=True)),
                ('dokumen_surat_domisili', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('siswa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='domisili', to='siswa.siswa')),
            ],
        ),
        migrations.CreateModel(
            name='JalurPendaftaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jalur', models.CharField(choices=[('domisili', 'Jalur Domisili'), ('afirmasi', 'Jalur Afirmasi'), ('prestasi', 'Jalur Prestasi'), ('mutasi', 'Jalur Mutasi')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('siswa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jalur_pendaftaran', to='siswa.siswa')),
            ],
        ),
        migrations.CreateModel(
            name='Wali',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_wali', models.CharField(blank=True, max_length=100, null=True)),
                ('nik_wali', models.CharField(blank=True, max_length=16, null=True)),
                ('pendidikan_wali', models.CharField(blank=True, max_length=20, null=True)),
                ('pekerjaan_wali', models.CharField(blank=True, max_length=50, null=True)),
                ('penghasilan_wali', models.CharField(blank=True, max_length=50, null=True)),
                ('telepon_wali', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('siswa', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wali', to='siswa.siswa')),
            ],
        ),
    ]
